server:
  port: 9000

spring:
  application:
    name: auth-server

  liquibase:
    change-log: /db/db.changelog-master.yaml

  datasource:
    url: jdbc:postgresql://localhost:5436/auth_server_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10

jwt:
  validateTimeForAccessToken: 3600
  validateTimeForRefreshToken: 2592000
  secretKey: Hala_Madrid
  resourceServerUrl: http://localhost:8080

resource-server:
  url:
    - http://resource-server:8080
    - http://localhost:8080