server:
  port: 9000

spring:
  application:
    name: auth-server
  autoconfigure:
    exclude:
    - org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
    - org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

resource-server:
  url:
    - http://resource-server:8080
    - http://localhost:8080