services:

  auth-server:
    build:
      context: ../auth_server
    container_name: auth-server
    ports:
      - "9000:9000"
      - "5005:5005"


  resource-db:
    image: postgres:16
    container_name: resource-db
    environment:
      POSTGRES_DB: resource_server_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5435:5432"
    volumes:
      - resource_data:/var/lib/postgresql/data
      - ./resource_db.sql:/docker-entrypoint-initdb.d/resource_db.sql

volumes:
  resource_data: